apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reference-wallet.fullname" . }}-web
  labels:
    app: {{ include "reference-wallet.fullname" . }}-web
    {{- include "reference-wallet.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "reference-wallet.fullname" . }}-web
      {{- include "reference-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "reference-wallet.fullname" . }}-web
        {{- include "reference-wallet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reference-wallet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-wait
        image: "{{ .Values.images.backend }}"
        command: ["sh", "-c", '/wait.sh {{ .Values.liquidityProviderHost }} {{ .Values.liquidityProviderPort }} || exit 1']
        imagePullPolicy: {{ .Values.images.pullPolicy }}
      containers:
      - command:
          - /wallet/run_web.sh
        env:
        - name: COMPOSE_ENV
          value: "production"
        - name: WALLET_PORT
          value: {{.Values.service.targetPort | quote}}
        - name: DB_URL
          value: {{ include "reference-wallet.peripherals.database.url" . }}
        - name: ADMIN_USERNAME
          value: {{ .Values.walletAdminUsername }}
        - name: WALLET_CUSTODY_ACCOUNT_NAME
          value: {{ .Values.custodyWalletAccountName | quote }}
        - name: CUSTODY_PRIVATE_KEYS
          value: {{ include "reference-wallet.custodyPrivateKeys" . }}
        - name: LIQUIDITY_SERVICE_PORT
          value: {{ .Values.liquidityProviderPort | quote }}
        - name: LIQUIDITY_SERVICE_HOST
          value: {{ .Values.liquidityProviderHost | quote }}
        - name: FAUCET_URL
          value: {{ .Values.sdk.faucet }}
        - name: VASP_ADDR
          value: {{ required "Wallet VASP account address must be set in .Values.vaspAddr" .Values.vaspAddr | quote }}
        - name: VASP_COMPLIANCE_KEY
          value: {{ required "Wallet VASP compliance key must be set in .Values.vaspComplianceKey" .Values.vaspComplianceKey | quote }}
        - name: JSON_RPC_URL
          value: {{ .Values.sdk.jsonRpc }}
        - name: VASP_BASE_URL
          value: http://{{ .Values.ingress.host }}/api/offchain
        - name: CHAIN_ID
          value: {{ .Values.chainId | quote }}
        - name: GAS_CURRENCY_CODE
          value: {{ .Values.gasCurrencyCode }}
        image: "{{ .Values.images.backend }}"
        name: lrw-web
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
          - name: http
            containerPort: {{.Values.service.targetPort}}
            protocol: TCP
