{{- if .Values.ingress.enabled -}}
{{- $fullName := include "libra-reference-wallet.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-backend
  labels:
    {{- include "libra-reference-wallet.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/api"
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ include "libra-reference-wallet.fullname" . }}-web
            servicePort: {{ .Values.service.port }}
          path: /api(/|$)(.*)
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-offchain
  labels:
    {{- include "libra-reference-wallet.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /offchain$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/offchain"
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ include "libra-reference-wallet.fullname" . }}-web
            servicePort: {{ .Values.service.offchainPort }}
          path: /offchain(/|$)(.*)
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "libra-reference-wallet.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ include "libra-reference-wallet.fullname" . }}-frontend
            servicePort: {{ .Values.service.port }}
          path: /
{{- end }}
